version: "3.8"

services:

  lembot:
    container_name: "lembot"
    image: "leminee/lembot:latest"
    restart: "always"
    depends_on:
      - "database"
    networks:
      - "lembot"

  database:
    container_name: "database"
    image: "mariadb:10.11"
    restart: "always"
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "no"
      MYSQL_DATABASE: "lembot"
      MYSQL_USER: "lembot"
      MYSQL_PASSWORD: "lembot"
    volumes:
      - "lembot:/var/lib/mysql"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - "lembot"

  phpmyadmin:
    image: "phpmyadmin:5.2.0"
    container_name: "PhpMyAdmin"
    restart: "always"
    depends_on:
      - "database"
    ports:
      - "80:80"
    environment:
      - "PMA_ARBITRARY=1"
    networks:
      - "lembot"


networks:
  lembot:
    driver: "bridge"
volumes:
  lembot: